# Continuous Integration (CI) and Continuous Delivery (CD) for PW.LibUA

trigger:
  batch: true
  branches:
    include:
    - release/pw-libua
  paths:
    exclude:
    - .gitignore
    - LICENSE
    - README.md

# Use templates from the Utilities/PipelinesTemplates repository
resources:
  repositories:
  - repository: PipelinesTemplates
    type: git
    name: Utilities/PipelinesTemplates

# Pipeline name
name: PW.LibUA.$(Build.BuildId)

stages:
- stage: Build
  jobs:
  - template: /DotNet/Build+Test.yml@PipelinesTemplates
    parameters:
      projectTitle: PW.LibUA
      libraryTitle: Libraries
      libraryProjects: |
        NET Core/LibUA/LibUA.csproj
      nugetFeedConnections:
      - name: paulwurth
        authenticate: true
        url: https://pkgs.dev.azure.com/paulwurth/_packaging/paulwurth/nuget/v3/index.json

# Only publish package(s) from release/pw-libua branch
- ${{ if in(variables['Build.SourceBranch'], 'refs/heads/release/pw-libua') }}:
  - stage: Publish
    jobs:
    - template: /DotNet/PublishNuGet.yml@PipelinesTemplates
      parameters:
        projectTitle: PW.LibUA
        packageTitle: Packages
        environment: Publish-PW_LibUA-Env
        packagesToPublish: |
          **/PW.LibUA.*.nupkg
